import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export async function getServerSideProps() {
  // const dataNota = await fetch(
  //   "https://admin.prensaobrera.com/wp-json/wp/v2/posts?&per_page=5&_embed"
  // );
  // const notas = await dataNota.json();
  return {
    props: {
      notas: "sdasdas",
    },
  };
}

export const Home = ({ notas }) => {
  console.log(notas);
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <main className={styles.main}>
          <h1>Prensa Obrera Demo Next</h1>
          {/* {notas.map((item) => item.title.rendered)} */}
          <Link href="/about">
            <a>About</a>
          </Link>
        </main>
      </div>
    </>
  );
};

export default Home;
